ARDUINO_DIR  = /usr/share/arduino
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = $(ARDUINO_DIR)/hardware/tools/avrdude.conf
TARGET       = temperature
ARDUINO_LIBS = ds18b20 OneWire
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
USER_LIB_PATH = $(HOME)/sketchbook/libraries

include $(HOME)/projects/arduino/Arduino.mk